### ISSUE TITLE
It becomes default value when receiving accept-language without Locale

### ISSUE THREAD

**Issue by kazkondo** [smhg/express-locale#14]
accept-language en-GB -> en-GB
accept-language ja -> en-US

**Comment by smhg** [comment]
Language-only locales are not supported (because they are often not useful). You need to provide a mapping of languages to full locales. E.g.:
```javascript
{
  map: {
    ja: 'ja_JP'
  }
}
```

**Comment by kazkondo** [comment]
But Google Chrome always return 'ja' in Japanese Environment, so your module always returns "en-US" as default. In Japan, There is no locale ( only Japan, mean ja-JP is the only language-locale ) so we often use only 'ja'. I think there is a language which has a related situation in the world. I understand what you mean, but that problem comes from historical things of browser and that always causes problem for us. always At least you should implement the mapping in the module from the first ( not option ).

FYI

My Google Chrome laungage setting : Japanese, English(US), English
-> Accept-Language Header : ja,en-US;q=0.9,en;q=0.8

**Comment by smhg** [comment]
I think there are some misconceptions in your view on this module (or locales in general).

This is not related to browsers.

Regions(/countries)/languages are not set in stone. They change.
That means some languages might only be related to one region _now_ but not tomorrow.
There is no such thing as a fixed list of locales where there is only one region for one language _forever_.

The idea is that your provide what your project's defaults are. You know your project best.

It comes down to this in your example:
What happens when a new region is added where Japanese is spoken?
`express_locale` shouldn't decide this for you.

**Comment by kazkondo** [comment]
I understand what you meant to say. But if the module needs to determine the "locale" by Accept-"Language" header of web browser, the module should return most relate "locale," isn't it? for example, en -> en-US ( of cause someone would say this should be en-GB!) , fr-> fr-FR, ja -> ja-JP. So I think that it would be better your module supports the default mapping list which can be replaced by users, or at least the module should not return "en-US" if there is no locale if that is your policy. I think that current spec causes just confusing for module users.

**Comment by smhg** [comment]
What is the "most related" region for `en`? Or for `fr`?
It depends on your project.

`en_US` is only returned because you allow it to be returned. There is a property `allowed` which should _not_ contain `en_US` in your case.

Based on the information you provided, your configuration should be something like:
```javascript
{
  priority: ['accept-language', 'map', 'default'],
  map: {
    ja: 'ja_JP'
  },
  default: 'ja_JP',
  allowed: ['ja_JP']
}
```
But, I assume you support at least one additional locale? If not, you don't even need this module.
