### ISSUE TITLE
allow for setting language not based on region

### ISSUE THREAD

**Issue by HoneyryderChuck** [smhg/express-locale#8]
I've seen that if I set a language without the region (like 'pt' instead of 'pt-BR' or 'en' instead of 'en-US') in the cookie, the locale isn't properly set. 

Is there a way to disable this? Is this a bug or an unimplemented feature?

**Comment by smhg** [comment]
I think this is by design. But you'd have to show your code.

The goal is to end up with a 'full' locale (language-REGION).
The `map` parameter is important in this respect. Should you not care about the region, then supply a default one for each language you don't care about (e.g. `map: {pt: pt-BR, en: en-US}`). Be sure to give this a try.

**Comment by HoneyryderChuck** [comment]
I guess you mean [this](https://github.com/smhg/express-locale/blob/master/test/index.js#L137-L139). So, I'll map a locale only to a locale-region pair?

**Comment by smhg** [comment]
Sorry about the late response.
You indeed have to supply your own mapping. There is no default (see [readme](https://github.com/smhg/express-locale#map)).

As in my example above, the mapping turns language-only values into full locales.
If you only care about the language, you can then get it by using `req.locale.language` in your script. So even if someone visits with pt-PT, you'll never care, You just don't use `req.locale.region`.
