### ISSUE TITLE
Error: Cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by HoneyryderChuck** [smhg/express-locale#9]
I'm getting this error when running in production after transpiling my code (no babel-node anymore). 

This happens not only because of that, but because babel-polyfill is listed as a dev-dependency, but it leaked into the transpiled file.

**Comment by lvl99** [comment]
I got this too. It seems unnecessary to have the `require('babel-polyfill')` if running on later node versions (I'm using 8.1.2).

Seems like it'd make sense to have a transpiled version available, rather than an ES6 file that relies on Babel when babel is not needed for later versions of Node (well, depending on the features required...).

**Comment by smhg** [comment]
Thank you both for reporting this. I'll try to find a better solution next week.
Feel free to send in a PR of course.

**Comment by smhg** [comment]
This should be fixed in 1.0.2. Thanks guys!

**Comment by smhg** [comment]
FYI: the published code is transpiled.

The ES6 source isn't even included. This means you can't do something like
`import createLocaleMiddleware from 'express-locale/src/index.js';`
to use the untranspiled version. Is there a need for this?

**Comment by HoneyryderChuck** [comment]
@smgh you could distribute both versions, as some libs do. The ES6 one will enable tree shaking in the future. But I'd say you could prioritize the transpired version for now.
